# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'three-days-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for three-days-iOS
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'  
  pod 'KeychainAccess'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
end
